#! /bin/sh
setxkbmap -option caps:escape

#kill all programs
pkill sxhkd
pkill picom
pkill dunst
pkill kdeconnect
pkill polybar
pkill nm-applet
pkill xfce4-clipman
pkill redshift

#autostart
$HOME/.config/polybar/launch.sh
#$HOME/Clones/hideIt.sh --name '^Polybar tray window$' --wait --direction bottom --steps 2 --signal --peek 2 --region 400x1080+1120+-20 &
$HOME/Clones/picom/build/src/picom -f -D 5 -i 0.9&
#compton -f -D 5 & 
redshift -l 27.2046:77.4977 &
#redshift -l 40.7128:-74.0060 & 

dunst &
xfce4-clipman &
kdeconnect-indicator &
nitrogen --restore
nm-applet &
sxhkd &
#/opt/miscellaneous/floating.sh &
#. "${HOME}/.cache/wal/colors.sh"

#bspwm
bspc monitor -d I II III IV V VI VII VIII IX 

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focused_border_color "000" 


# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"


#/opt/miscellaneous/monocle.sh & ; disown %1
bspc config external_rules_command "/home/cody/.config/bspwm/external_rules"
