#! /bin/sh
setxkbmap -option caps:escape

$HOME/.config/bspwm/monitor.sh >> /tmp/monitor.log & 

#kill all programs
pkill sxhkd
pkill picom
pkill dunst
pkill kdeconnect
pkill polybar
pkill nm-applet
pkill xfce4-clipman

pkill redshift
pkill redshift
# pkill discord

## GO bin
PATH="$PATH:/usr/local/go/bin"

##autostart
#Polybar
$HOME/.config/polybar/colorblocks/scripts/pywal.sh $(cat .fehbg | grep -oE "'.*'")
$HOME/.config/polybar/colorblocks/launch.sh

tmux kill-session -t new_session
tmux new-session -d -s new_session '/home/buddha/.config/scripts/reverse_server.sh' &

ps -aux | grep battery-status.sh | awk '{print $2}' | xargs kill -9
$HOME/.config/scripts/battery-status.sh &
# $HOME/Clones/picom/build/src/picom & 
picom --experimental-backends --backend glx &
~/.fehbg &
dunst &
xfce4-clipman &
nm-applet &
sxhkd &
# discord &
#/opt/miscellaneous/floating.sh &
/opt/miscellaneous/drive_sync.sh &
# ./"${HOME}/.cache/wal/colors.sh"

#bspwm

bspc config border_width         0
bspc config window_gap          5

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^4'
bspc rule -a vlc desktop='^5' follow=on
bspc rule -a mpv desktop='^5' follow=on
bspc rule -a ViberPC desktop='^6' follow=on
bspc rule -a M2011K2G state=floating follow=on
bspc rule -a Google-chrome desktop='^7' follow=on
bspc rule -a Firefox-esr desktop='^1' follow=on
bspc rule -a scrcpy state=floating follow=no
bspc rule -a Gnome-calculator state=floating follow=on

#bspc config focused_border_color "123" 


# Set the border colors.
bspc config normal_border_color "$color15"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color1"


#/opt/miscellaneous/monocle.sh & ; disown %1
#bspc config external_rules_command "/home/buddha/.config/bspwm/external_rules"
